### ISSUE TITLE
Terimlerin Türkçe karşılıkları

### ISSUE THREAD

**Issue by koluacik** [haskellturkiye/lyah-tr#8]
Çeviriye yardımcı olmaya çalışırken belki de en çok zorlandığım kısım kitapta geçen terimler için Türkçe karşılık bulmaya çalışmak oldu. Bu konuda projeyle ilgilenen diğer kişilerin de fikrini sormak istiyorum.

Şimdiye kadar karşılaştığım terimler için çokuzlu veya karakter katarı gibi daha önceden başka kaynaklardan kulak aşinalığım olan karşılıkları kullandım ancak bunlar gibi karşılıkların derlendiği tek başına yeterli olabilecek bir kaynak bulamadığım gibi önerilen bu karşılıkların yaygınlığı ve geçerliliği hakkında da çok bilgim yok. Bir diğer seçenek de kelime bazında çeviri yapmak, ancak bu sefer de tip beyanı gibi kulağa hoş gelmeyen çevirilerle karşı karşıya kalınıyor ve bu şekilde yapılan çeviriler çevirilerin geçerliliği ve yaygınlığı problemini daha da büyütebiliyor.

Benim çözüm önerim terimleri kaynakta olduğu haliyle kullanmak ve bir terimin ilk defa kullanıldığı yerlerde çeviri yerine dipnotta çevirmenin notu şeklinde Türkçe tanım yapmak. Bu şekilde çevirilerdeki anlam kaybının azalacağı gibi çeviriyle uğraşan kişilerin de yükünün hafifleyeceğine inanıyorum.

**Comment by delirehberi** [comment]
"çokuzlu" ve "karakter katarı" çok uygun çeviriler olduğunu düşünmüyorum.

Önerine katılıyorum, ben de alışılmamış çeviriler yaparken orjinal kelimeyi parantez içerisinde yazıyorum.

Ek olarak istersen bir kelime listesi tutmaya başlayalım? Markdown tablo olarak şu şekilde.

|  İngilizce | Türkçe  |
|---|---|
| Exampe | Örnek |

**Comment by koluacik** [comment]
Kelime listesi olarak tutmak iyi bir fikir. Peki bunu yaparken cümle içinde orijinal kelimeyi mi kullanacağız yoksa yine kendi bulduğumuz çeviriyi mi kullanacağız?

**Comment by delirehberi** [comment]
Kelime listesi tutsak da "list comprehension" gibi kelimeleri parantez içinde de vermek daha doğru olacaktır gibi düşünüyorum.

**Comment by delirehberi** [comment]
Şu dosyayı direk master branch üzerinde düzenleyerek ilerleyebiliriz diye düşünüyorum https://github.com/haskellturkiye/lyah-tr/blob/master/dictionary.md

**Comment by koluacik** [comment]
> Kelime listesi tutsak da "list comprehension" gibi kelimeleri parantez içinde de vermek daha doğru olacaktır gibi düşünüyorum.

Doğru anladıysam şu şekilde mi olacak o zaman?

"A typeclass is a sort of interface that defines some behavior." -> "Tip sınıfı (typeclass) belli davranışları tanımlayan bir arayüz gibi düşünlebilir."

Eğer bu şekildeyse ilk yorumda bahsettiğim "[B]u şekilde yapılan çeviriler çevirilerin geçerliliği ve yaygınlığı problemini daha da büyütebiliyor." sorununu nasıl çözebiliriz? Çünkü bu haliyle de karşılaştığımız terimler için kendi kafamızdan karşılıklar önermiş oluyoruz.

**Comment by delirehberi** [comment]
Öncelikli hedefimiz anlaşılabilir bir haskell dökümanı oluşturmak olduğu için ve bu da bir başlangıç dökümanı olduğu için, anlaşılabilmesi adına türkçesini ve doğrusunun bilinmesi adına da ingilizcesinin eklenmesinin doğru olduğunu düşünüyorum. Türkçe'de yaygın olarak kelimeleri seçersek (katar,beyan vs gibi kelimeleri değil) geçerlilik ve yaygınlık konusunda sıkıntı olacağını düşünmüyorum.

**Comment by koluacik** [comment]
Öyleyse sözlük için bir tablo ve metin içinde parantez arasında orijinal terimi sunmak bence de yeterli olacaktır. Bu issue'yu kapatıyorum.
